/*
C++ Primer, Stanley B. Lippmann, 2013
Chapter 05. Statements

Exercise 5.25: Revise your program from the previous exercise to use a
try block to catch the exception. The catch clause should print a message
to the user and ask them to supply a new number and repeat the code inside
the try.

*/

#include <iostream>

int main() {
  //

  return 0;
}